### ISSUE TITLE
[checklist] pure node backend

### ISSUE THREAD

**Issue by coolaj86** [Daplie/node-letsencrypt#1]
It's coming along in the [`ursa`](https://github.com/Daplie/node-letsencrypt/tree/ursa) branch of node-letsencrypt and the `handshake-only` branch of letiny.

API looks good, needs minimal wrapping.

* [x] use `ursa` for the gruntwork of key generation
* [x] read renewals just like official client
* [x] write accounts just like official client
* [x] write registrations just like official client
* [x] update cli
* [x] allow `forge` as an option
* [ ] strip out `forge` helper functions except where absolutely neccessary

**Comment by coolaj86** [comment]
It's coming along in the `ursa` branch.
